# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
  - repo: local
    hooks:
      - id: vale
        name: Validate Style Guide with Vale
        description: Validate Style Guide with Vale
        language: docker_image
        entry: docker.io/jdkato/vale
        pass_filenames: true
        always_run: false
        verbose: true
        require_serial: false
