site:
  title: DAG-OS Documentation
  url: https://dag-os.gitlab.io/dagos
  start_page: design::index.adoc
content:
  sources:
    - url: ./
      start_paths:
        - docs/design
asciidoc:
  attributes:
    kroki-fetch-diagram: true
  extensions:
    - asciidoctor-kroki
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
