[tool.poetry]
name = "dagos"
version = "0.1.1"
description = "A CLI for defining and deploying software environments."
license = "MIT"
authors = ["Lucas Resch <lucas.resch@gmx.de>"]
maintainers = ["Lucas Resch <lucas.resch@gmx.de>"]

[tool.poetry.dependencies]
python = "^3.7"
click = "^8.0.3"
click-option-group = "^0.5.3"
rich = "^11.0.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^21.12b0"
pre-commit = "^2.16.0"
twine = "^3.7.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
