# This schema describes the structure of an environment definition file in the
# YAML format. It is based on the syntax defined by Yamale:
# https://github.com/23andMe/Yamale

environment:
  name: str()
  description: str(required=False)
  platform: include('platform')
  components: list(include('component'))
---
platform:
  os: any(include('os'), list(include('os')))
  images: list(include('image'), required=False)
os: enum('linux', 'windows')

image:
  # The fully qualifying ID of the image used for pulling it
  id: str(min=1, multiline=False)
  # A list of packages to install with the system package manager
  packages: include('packages', required=False)

packages: list(str())

component:
  name: str()
  purpose: str(required=False)
  version: str(required=False)
