[[section-introduction-and-goals]]
= Introduction and goals

[role="arc42help"]
****
Describes the relevant requirements and the driving forces that software architects and development team must consider. These include

* underlying business goals, essential features and functional requirements for the system
* quality goals for the architecture
* relevant stakeholders and their expectations
****

== Requirements overview

////
[role="arc42help"]
****
.Contents
Short description of the functional requirements, driving forces, extract (or abstract)
of requirements. Link to (existing) requirements documents
(with version number and information where to find it).

.Motivation
From the point of view of the end users a system is created or modified to
improve support of a business activity and/or improve the quality.

.Form
Short textual description, probably in tabular use-case format.
If requirements documents exist this overview should refer to these documents.

Keep these excerpts as short as possible. Balance readability of this document with potential redundancy w.r.t to requirements documents.
****
////

The main goal of this system is to provide individuals or development teams with the tools to create shared software environments for various purposes.
Such purposes may include creating shared development environments, staging environments, or deployment environments.

The system provides a framework for provisioning software components on supported operating system baselines to achieve this goal.
It may include common software components to bootstrap the environment definition process.

////
[options="header",cols="12%,~"]
.Requirements
|===
|ID|Description

|REQ-0001
|If at all possible, any actions the system takes should be *idempotent*.

|REQ-0002
|The system should log any actions it takes in a dedicated place to support basic auditing and debugging purposes.
|===
////

== Quality goals

////
[role="arc42help"]
****
.Contents
The top three (max five) quality goals for the architecture whose fulfillment is of highest importance to the major stakeholders. We really mean quality goals for the architecture. Don't confuse them with project goals. They are not necessarily identical.

.Motivation
You should know the quality goals of your most important stakeholders, since they will influence fundamental architectural decisions. Make sure to be concrete about these qualities, avoid buzzwords.
If you as an architect do not know how the quality of your work will be judged …

.Form
A table with quality goals and concrete scenarios, ordered by priorities
****
////

The following architecture quality goals are major influences for the design of the system ordered by priority.

[options="header",cols="1,4,4"]
.Quality goals
|===
|Quality goal|Description|Scenarios

|Simplicity
|The resulting software should be simple to use and reason about.
a|It's clear

* where things belong,
* how to configure them, and
* how to use them.

|Customizability
|Every user of the system will have their own requirements and preferences.
The system must be customizable to fit their needs.
|Users may prefer a certain vendor, require a specific version, or want to configure a software component in a specific way.

|Extensibility
|No matter how varied or how customizable the common software components are, users will always require something more.
It must be possible to extend the system to meet this need.
a| A user requires

* a software component that is not (yet) provided by the system,
* a specific version of a common software component that is not (yet) offered, or
* supplementary steps during the provisioning of a software component.

|Maintainability
|The maintenance of the system architecture and the created environments is a major concern.
The usage of the system highly depends on its reliability.
Both for the system itself but also the products it creates.
|Production use cases may require the provisioning of an environment years after its creation.
|===

== Stakeholders

////
[role="arc42help"]
****
.Contents
Explicit overview of stakeholders of the system, i.e. all person, roles or organizations that

* should know the architecture
* have to be convinced of the architecture
* have to work with the architecture or with code
* need the documentation of the architecture for their work
* have to come up with decisions about the system or its development

.Motivation
You should know all parties involved in development of the system or affected by the system.
Otherwise, you may get nasty surprises later in the development process.
These stakeholders determine the extent and the level of detail of your work and its results.

.Form
Table with role names, person names, and their expectations with respect to the architecture and its documentation.
****
////

The following stakeholders and their respective expectations influence the design of the system.

[options="header",cols="20%,~"]
.Stakeholders
|===
|Role|Expectations

// Maintainers?
// Quality managers?

|Environment creator
a|
* Defining a shared environment is simple.
** Common, configurable building blocks exist.
** Adding custom building blocks is simple.
** Extending common building blocks is possible?
* Extending environments is possible.
* Combining environments is possible.

|Environment user
a|
* Using a shared environment is simple.
** After choosing an environment and downloading it deploying it to the chosen context, e.g., a VM or WSL, is (semi)-automatic.
** They require no further setup.
* It's possible to deploy them in various contexts, e.g.,
** a bare metal installation of an operating system,
** a virtual machine,
** a container engine like Docker or Podman, or
** a WSL instance.
|===
