---
name: CI

on:
  push:
  schedule:
    - cron: "0 7 * * 2"

jobs:
  tox:
    name: Tox
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          # Disable shallow clone for SonarCloud
          fetch-depth: 0

      - name: Set up Python.
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Run image.
        uses: abatilo/actions-poetry@v2.1.4

      - name: Install dependencies.
        run: poetry install

      - name: Run Tox.
        run: poetry run tox

      - name: Log in to GitLab container registry.
        uses: redhat-actions/podman-login@v1
        with:
          username: gitlab+deploy-token-824041
          password: ${{ secrets.GITLAB_DAGOS_CONTAINER_REGISTRY_TOKEN   }}
          registry: registry.gitlab.com

      - name: Run integration tests.
        run: podman run --rm --volume .:/root/dagos registry.gitlab.com/dag-os/dagos/dagos-test-image

      - name: Generate coverage report.
        run: |
          poetry run coverage combine
          poetry run coverage report --show-missing
          poetry run coverage xml

      - name: SonarCloud scan.
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
