---
name: CI

on:
  push:
  schedule:
    - cron: "0 7 * * 2"

jobs:
  tox:
    name: Tox
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          # Disable shallow clone for SonarCloud
          fetch-depth: 0

      - name: Set up Python.
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Run image.
        uses: abatilo/actions-poetry@v2.1.4

      - name: Install dependencies.
        run: poetry install

      - name: Run Tox.
        run: poetry run tox

      - name: Generate coverage report.
        run: |
          poetry run coverage combine
          poetry run coverage xml

      - name: SonarCloud scan.
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
